import type { Metadata } from "next";
import { Roboto,Source_Sans_3 } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/navbar";

const source = Source_Sans_3({ subsets: ["latin"] });
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
 
export const metadata: Metadata = {
  title: "Ramit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${source.className}`}>   
          <NavBar/>
          {children}
      </body>
    </html>
  );
}
